# Use for local development only
version: '3.7'
services:
  postgres:
    container_name: arithmetic-calculator-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: ["postgres", "-c", "log_statement=all"]
